package com.bng.entity;

// Generated 5 Mar, 2014 2:37:46 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * MxgraphVersion generated by hbm2java
 */
@Entity
@Table(name = "mxgraph_version")
public class MxgraphVersion implements java.io.Serializable {

	private Integer id;
	private Integer version;
	private Mxdata mxdata;
	private Mxgraph mxgraph;
	private Integer userMappingId;
	private Date createdDate;

	public MxgraphVersion() {
	}

	public MxgraphVersion(Mxdata mxdata, Mxgraph mxgraph,
			Integer userMappingId, Date createdDate) {
		this.mxdata = mxdata;
		this.mxgraph = mxgraph;
		this.userMappingId = userMappingId;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mxdata_id")
	public Mxdata getMxdata() {
		return this.mxdata;
	}

	public void setMxdata(Mxdata mxdata) {
		this.mxdata = mxdata;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mxgraph_id")
	public Mxgraph getMxgraph() {
		return this.mxgraph;
	}

	public void setMxgraph(Mxgraph mxgraph) {
		this.mxgraph = mxgraph;
	}

	@Column(name = "user_mapping_id")
	public Integer getUserMappingId() {
		return this.userMappingId;
	}

	public void setUserMappingId(Integer userMappingId) {
		this.userMappingId = userMappingId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
