package com.bng.entity;

// Generated 5 Mar, 2014 2:37:46 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ObdCli generated by hbm2java
 */
@Entity
@Table(name = "obd_cli")
public class ObdCli implements java.io.Serializable {

	private Integer id;
	private Service service;
	private String cli;

	public ObdCli() {
	}

	public ObdCli(Service service, String cli) {
		this.service = service;
		this.cli = cli;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cli_id", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@Column(name = "cli", nullable = false, length = 25)
	public String getCli() {
		return this.cli;
	}

	public void setCli(String cli) {
		this.cli = cli;
	}

}
