package com.bng.entity;

// Generated 13 Nov, 2013 1:13:35 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ObdCli generated by hbm2java
 */
@Entity
@Table(name = "obd_cli")
public class ObdCli implements java.io.Serializable {

	private int id;
	private Service service;
	private String cli;

	public ObdCli() {
	}

	public ObdCli(int id, Service service, String cli) {
		this.id = id;
		this.service = service;
		this.cli = cli;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cli_id", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@Column(name = "cli", nullable = false, length = 25)
	public String getCli() {
		return this.cli;
	}

	public void setCli(String cli) {
		this.cli = cli;
	}

}
